services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./hello-world-theme:/var/www/html/wp-content/themes/hello-world-theme
      - ./scripts:/scripts
    entrypoint: ["/scripts/entrypoint.sh"]

  db:
    image: mysql:9.2.0
    container_name:
     wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
